import{triage,decisionRecord,VERSION}from'./core.js';
const q=new URLSearchParams(location.search);let lang=q.get('lang')==='es'?'es':'en',data={country:'',sector:'',size:'',exception:'none',multiCountry:false,designated:'unknown',name:'',owner:'',purpose:'',notes:''};
const t=(en,es)=>lang==='es'?es:en,el=id=>document.getElementById(id),countries={AT:'Austria',BE:'Belgium',BG:'Bulgaria',HR:'Croatia',CY:'Cyprus',CZ:'Czechia',DK:'Denmark',EE:'Estonia',FI:'Finland',FR:'France',DE:'Germany',GR:'Greece',HU:'Hungary',IE:'Ireland',IT:'Italy',LV:'Latvia',LT:'Lithuania',LU:'Luxembourg',MT:'Malta',NL:'Netherlands',PL:'Poland',PT:'Portugal',RO:'Romania',SK:'Slovakia',SI:'Slovenia',ES:'Spain',SE:'Sweden'};
function localise(){document.documentElement.lang=lang;document.querySelectorAll('[data-en]').forEach(x=>x.textContent=x.dataset[lang]);el('language').textContent=lang==='en'?'ES':'EN'}
function capture(){document.querySelectorAll('[data-key]').forEach(x=>data[x.dataset.key]=x.type==='checkbox'?x.checked:x.value)}
function render(){el('country').innerHTML=`<option value="">${t('Select country','Selecciona país')}</option>`+Object.entries(countries).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');Object.entries(data).forEach(([k,v])=>{const x=document.querySelector(`[data-key="${k}"]`);if(x)x.type==='checkbox'?x.checked=v:x.value=v});localise()}
function show(){capture();const r=triage(data),labels={unresolved:t('Unresolved','Sin resolver'),'not-indicated':t('Not indicated by this screen','No indicado por este filtro'),'potentially-in-scope':t('Potentially in scope','Potencialmente dentro del alcance'),'needs-national-review':t('National review required','Requiere revisión nacional')},cats={unresolved:t('Category unresolved','Categoría sin resolver'),'potentially-essential':t('Potential essential entity','Posible entidad esencial'),'potentially-important':t('Potential important entity','Posible entidad importante')};el('result').hidden=false;el('result').innerHTML=`<div class="result-head"><div><p class="eyebrow">${t('QUALIFIED PRELIMINARY OUTCOME','RESULTADO PRELIMINAR CUALIFICADO')}</p><h2>${labels[r.status]}</h2><p>${cats[r.category]} · ${t('Confidence','Confianza')}: <b>${r.confidence}</b></p></div><span class="pill">v${VERSION}</span></div>${list(t('Decision basis','Fundamento'),r.reasons)}${list(t('Uncertainties','Incertidumbres'),r.uncertainties)}${list(t('Next actions','Próximas acciones'),r.actions)}<div class="exports"><button id="json">JSON</button><button id="md">Markdown</button><button onclick="print()">${t('Print / PDF','Imprimir / PDF')}</button></div><p class="warning">${t('This result is not a final legal determination. National transposition, designation and sector rules must be verified.','Este resultado no es una determinación jurídica final. Deben verificarse la transposición nacional, la designación y las reglas sectoriales.')}</p>`;el('json').onclick=()=>download('nis2-applicability-record.json',JSON.stringify(decisionRecord(data,r),null,2),'application/json');el('md').onclick=()=>download('nis2-applicability-record.md',md(r),'text/markdown');el('result').scrollIntoView({behavior:'smooth'})}
const list=(h,a)=>a?.length?`<section><h3>${h}</h3><ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul></section>`:'';
function md(r){return`# NIS2 applicability triage\n\n- Version: ${VERSION}\n- Country: ${data.country}\n- Organisation: ${data.name}\n- Owner: ${data.owner}\n- Status: ${r.status}\n- Category: ${r.category}\n- Confidence: ${r.confidence}\n\n## Decision basis\n${r.reasons.map(x=>`- ${x}`).join('\n')}\n\n## Uncertainties\n${r.uncertainties.map(x=>`- ${x}`).join('\n')}\n\n_Preliminary triage only; not legal advice._`}
function download(n,c,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type}));a.download=n;a.click()}
el('run').onclick=show;el('demo').onclick=()=>{data={country:'ES',sector:'health',size:'medium',exception:'none',multiCountry:true,designated:'unknown',name:'DemoCo Health Cloud',owner:'GRC Manager',purpose:'Cloud platform supporting healthcare service delivery in Spain and another EU Member State.',notes:'Fictional worked example.'};render();show()};el('language').onclick=()=>{lang=lang==='en'?'es':'en';q.set('lang',lang);history.replaceState(null,'',`${location.pathname}?${q}`);localise()};render();
