export const VERSION='1.0.0';
export const ANNEX_I=['energy','transport','banking','financial','health','drinking-water','waste-water','digital-infrastructure','ict-management','public-administration','space'];
export const ANNEX_II=['postal','waste-management','chemicals','food','manufacturing','digital-providers','research'];
export const SIZE_INDEPENDENT=['electronic-communications','trust-services','tld-dns','sole-provider','public-safety','systemic-risk','national-designation'];
export function triage(a={}){const reasons=[],uncertainties=[],actions=[];let status='unresolved',category='unresolved',confidence='medium';
 if(!a.country||!a.sector){return{status,category,confidence:'low',reasons,uncertainties:['Country and sector are required.'],actions:['Complete the jurisdiction and sector screen.']}}
 const annex=ANNEX_I.includes(a.sector)?'I':ANNEX_II.includes(a.sector)?'II':null,exception=SIZE_INDEPENDENT.includes(a.exception),medium=['medium','large'].includes(a.size);
 if(!annex&&!exception){status='not-indicated';confidence='medium';reasons.push('No Annex I/II sector or size-independent route was selected.');uncertainties.push('National scope extensions and entity-specific designation remain possible.');}
 else if(medium||exception){status='potentially-in-scope';category=annex==='I'&&a.size==='large'||['trust-services','tld-dns','public-administration'].includes(a.exception)?'potentially-essential':'potentially-important';reasons.push(annex?`Selected activity maps preliminarily to Annex ${annex}.`:'A size-independent route was selected.');reasons.push(exception?'The selected route may apply regardless of size.':'The organisation meets the selected medium/large size band.');actions.push('Validate the exact entity type and service against national transposition law.','Confirm main establishment, registration and competent authority.','Create a documented applicability decision with legal review.');}
 else{status='needs-national-review';category='unresolved';confidence='low';reasons.push(`A potential Annex ${annex} activity was selected, but the organisation is below the standard size threshold.`);uncertainties.push('Member States may identify smaller entities with a high-risk profile.');actions.push('Check national designation and sector-specific rules.');}
 if(a.multiCountry)uncertainties.push('Cross-border operations require main-establishment and jurisdiction analysis.');if(a.designated==='unknown')uncertainties.push('Entity-specific national designation is unresolved.');if(uncertainties.length>1)confidence='low';
 return{status,category,confidence,reasons,uncertainties,actions,annex};}
export function decisionRecord(a,r){return{schema:'spectrasec.nis2.applicability-record',version:VERSION,generatedAt:new Date().toISOString(),assessment:a,result:r,disclaimer:'Preliminary triage only; not legal advice or a final applicability determination.'}}
