export const MODULE_VERSION='1.2.0';
const pending=(code,name)=>({code,name,status:'pending',reviewed:null,summaryEn:'EU baseline assessment available. National legal module has not yet been verified.',summaryEs:'Evaluación europea disponible. El módulo jurídico nacional todavía no ha sido verificado.',sources:[],questions:[]});
export const MODULES={
 ES:{code:'ES',name:'Spain',status:'partial',reviewed:'2026-08-25',summaryEn:'Official Spanish sources re-reviewed on 2026-08-25. NIS2 transposition and final national rules on competent authorities, registration and designation still require confirmation.',summaryEs:'Fuentes oficiales españolas revisadas de nuevo el 2026-08-25. La transposición NIS2 y las reglas nacionales definitivas sobre autoridades, registro y designación aún requieren confirmación.',sources:[['DSN — draft Cybersecurity Coordination and Governance Law','https://www.dsn.gob.es/es/actualidad/sala-de-prensa/anteproyecto-ley-coordinacion-gobernanza-ciberseguridad'],['INCIBE-CERT — NIS2 FAQ','https://www.incibe.es/incibe-cert/sectores-estrategicos/FAQNIS2'],['BOE — Cybersecurity Law Code','https://www.boe.es/biblioteca_juridica/codigos/codigo.php?id=173']],questions:[['esPublic','Subject to the Spanish National Security Framework (ENS)?','¿Está sujeta al Esquema Nacional de Seguridad (ENS)?'],['esOperator','Previously identified as an essential service or critical operator?','¿Fue identificada previamente como operador esencial o crítico?'],['esRegister','Registered or contacted by a Spanish sector authority?','¿Está registrada o ha sido contactada por una autoridad sectorial española?'],['esIncident','Current incident channel assigned to INCIBE-CERT, CCN-CERT or sector CSIRT?','¿Tiene canal de incidentes asignado a INCIBE-CERT, CCN-CERT o CSIRT sectorial?'] ]},
 DE:{...pending('DE','Germany'),status:'planned',summaryEn:'German authority directory available; national decision logic is planned and must not be treated as verified.',summaryEs:'Directorio de autoridades alemán disponible; la lógica nacional está planificada y no debe considerarse verificada.'},
 FR:{...pending('FR','France'),status:'planned',summaryEn:'French authority directory available; national decision logic is planned and must not be treated as verified.',summaryEs:'Directorio francés disponible; la lógica nacional está planificada y no debe considerarse verificada.'},
 IT:{...pending('IT','Italy'),status:'planned'},NL:{...pending('NL','Netherlands'),status:'planned'},IE:{...pending('IE','Ireland'),status:'planned'},PT:{...pending('PT','Portugal'),status:'planned'}
};
export function nationalModule(code,name=''){return MODULES[code]||pending(code,name)}
export function nationalAssessment(code,answers={}){const m=nationalModule(code);const answered=Object.values(answers).filter(Boolean).length;return{moduleVersion:MODULE_VERSION,country:code,status:m.status,reviewed:m.reviewed,answered,totalQuestions:m.questions.length,conclusion:m.status==='partial'?'National validation required — official sources reviewed but final rules are not fully implemented.':'EU baseline only — national module pending.',sources:m.sources}}
