import{profile}from'./countries.js';
export const VERSION='1.2.0';
export const ANNEX={energy:'I',transport:'I',banking:'I',financial:'I',health:'I','drinking-water':'I','waste-water':'I','digital-infrastructure':'I','ict-management':'I','public-administration':'I',space:'I',postal:'II','waste-management':'II',chemicals:'II',food:'II',manufacturing:'II','digital-providers':'II',research:'II'};
const ALWAYS=['electronic-communications','trust-services','tld-dns','sole-provider','public-safety','systemic-risk','national-designation','cer-critical'];
export function sizeBand({employees=0,turnover=0,balance=0,linked=false,sizeOverride=''}){if(sizeOverride)return{band:sizeOverride,source:'override'};const e=+employees,t=+turnover,b=+balance;if(!e&&!t&&!b)return{band:'unknown',source:'missing'};let band=e>=250||t>50||b>43?'large':e>=50||t>10||b>10?'medium':e>=10||t>2||b>2?'small':'micro';return{band,source:'calculated',linkedReview:!!linked}}
export function assess(a={}){const c=profile(a.country),size=sizeBand(a),annex=ANNEX[a.sector]||null,reasons=[],discarded=[],uncertainties=[],actions=[];let status='unresolved',category='unresolved',jurisdiction=a.mainEstablishment||a.country||'unresolved';
 if(!c||!a.entityType||!a.sector){return{status,category,jurisdiction,size,annex,reasons,discarded,uncertainties:['Country, entity type and sector are required.'],actions:['Complete the mandatory scope facts.'],country:c}}
 const special=ALWAYS.includes(a.specialRoute),standard=['medium','large'].includes(size.band),excluded=a.exclusion&&a.exclusion!=='none';
 if(excluded){uncertainties.push('A potential Article 2 exclusion was selected; validate every condition and national implementation.');}
 if(a.dora)uncertainties.push('DORA may operate as sector-specific lex specialis for overlapping cybersecurity risk-management and incident-reporting requirements; map residual NIS2 duties.');
 if(!annex&&!special){status='not-indicated';reasons.push('No Annex I/II activity or size-independent route was identified.');discarded.push('Standard sector route');uncertainties.push('National extensions or designation may still apply.');}
 else if(standard||special){status='potentially-in-scope';reasons.push(annex?`Activity maps preliminarily to Annex ${annex}.`:'A special scope route was selected.');reasons.push(special?'Selected route may apply regardless of size.':`Calculated size band is ${size.band}.`);category=annex==='I'&&size.band==='large'||['trust-services','tld-dns','public-administration','cer-critical'].includes(a.specialRoute)?'potentially-essential':'potentially-important';if(category==='potentially-important')discarded.push('Essential-entity route not established on current facts');}
 else{status='national-review';reasons.push(`Potential Annex ${annex} activity, but the ${size.band} band is below the standard threshold.`);uncertainties.push('National designation or a size-independent route may bring the entity into scope.');}
 if(size.band==='unknown')uncertainties.push('Size cannot be determined from the supplied evidence.');if(size.linkedReview)uncertainties.push('Linked/partner enterprise aggregation requires validation under the SME rules.');if(a.multiCountry&&!a.mainEstablishment)uncertainties.push('Main establishment is unresolved for cross-border services.');if(a.specialJurisdiction)jurisdiction=a.mainEstablishment||'main-establishment review';
 actions.push('Verify the national transposition law and exact entity definition.','Confirm competent sector authority and registration requirements.','Obtain independent review and approval of the decision record.');return{status,category,jurisdiction,size,annex,reasons,discarded,uncertainties,actions,country:c,confidence:uncertainties.length>2?'low':uncertainties.length?'medium':'high'};}
export function record(a,r){return{schema:'spectrasec.nis2.applicability-decision-record',version:VERSION,generatedAt:new Date().toISOString(),system:{id:a.recordId,organisation:a.name,service:a.service,entityType:a.entityType},governance:{owner:a.owner,reviewer:a.reviewer,approver:a.approver,nextReview:a.nextReview,status:a.approvalStatus},assessment:a,result:r,history:[...(a.history||[]),{at:new Date().toISOString(),event:'generated'}],sources:['https://eur-lex.europa.eu/eli/dir/2022/2555/oj/eng',r.country?.authorityUrl,r.country?.enisa].filter(Boolean),disclaimer:'Qualified preliminary triage only; not a final legal determination or legal advice.'}}
