import{mkdir,writeFile}from'node:fs/promises';import{COUNTRIES,REVIEWED}from'../countries.js';
const base='https://cyber-g3.github.io/nis2-applicability-triage-by-country';
const shell=({title,description,path,body,lang='en',robots='index,follow'})=>`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta name="robots" content="${robots}"><link rel="canonical" href="${base}/${path}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="article"><meta property="og:image" content="${base}/assets/social-preview.jpg"><style>body{font:18px/1.65 system-ui;max-width:900px;margin:60px auto;padding:24px;color:#142536}a{color:#0b6657}.cta{display:inline-block;background:#0b6657;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none}.note{background:#edf5f3;padding:18px;border-radius:10px}nav{display:flex;gap:18px;flex-wrap:wrap}</style></head><body><nav><a href="${base}/">NIS2 Scope Tool</a><a href="https://cyber-g3.github.io/-nis2-incident-reporting-timeline./">NIS2 Incident</a><a href="https://cyber-g3.github.io/audit-evidence-readiness-checker/">Audit Evidence</a><a href="https://cyber-g3.github.io/eu-ai-act-risk-classifier/">EU AI Act</a></nav>${body}<p><a class="cta" href="${base}/">Open the NIS2 assessment →</a></p><p class="note">Decision support only. Validate current national law, competent-authority guidance and the facts of the organisation.</p></body></html>`;
const intents=[
 ['nis2-size-threshold','NIS2 size threshold explained','How employee count, annual turnover, balance sheet and linked enterprises affect the NIS2 size-cap assessment.','<h1>NIS2 size threshold</h1><p>The EU baseline generally connects scope to medium-sized or larger entities in covered sectors, but special routes and national rules can change the result.</p><h2>What to document</h2><ul><li>Employees, turnover and balance sheet.</li><li>Partner and linked enterprises.</li><li>Sector, entity type and special inclusions.</li><li>Member State and establishment.</li></ul><h2>FAQ</h2><h3>Does NIS2 apply to small companies?</h3><p>Sometimes. Certain entity types, criticality or national designation routes can apply independently of the standard size threshold.</p>'],
 ['essential-vs-important-entity','NIS2 essential vs important entity','Understand essential and important entities, supervision and the evidence needed for classification.','<h1>Essential vs important entity under NIS2</h1><p>Classification depends on sector, entity type, size and national implementation. Both categories have cybersecurity risk-management and incident-reporting duties, while supervision and sanctions can differ.</p><h2>Decision record</h2><p>Keep the sector mapping, size calculation, special-route analysis, jurisdiction and official sources used.</p>'],
 ['nis2-for-managed-service-providers','NIS2 for managed service providers','A practical scope screen for MSP and MSSP providers under the NIS2 Directive.','<h1>NIS2 for managed service providers</h1><p>Managed service and managed security service providers are expressly relevant entity types. Scope still requires analysis of services, size, establishment and national transposition.</p>'],
 ['nis2-for-healthcare','NIS2 for healthcare','Screen healthcare organisations for NIS2 sector, entity, size and jurisdiction routes.','<h1>NIS2 for healthcare</h1><p>Healthcare coverage may include healthcare providers, reference laboratories and certain research or manufacturing entities. Document the exact entity type and national rules.</p>'],
 ['nis2-for-saas','NIS2 for SaaS companies','Assess SaaS scope through cloud, data centre, managed service or other NIS2 categories.','<h1>NIS2 for SaaS companies</h1><p>“SaaS” alone is not a legal category. Analyse the actual service model, infrastructure role, customer commitments, size and Member State establishment.</p>']
];
const urls=[`${base}/`,`${base}/en/`,`${base}/es/`];
for(const[slug,title,description,body]of intents){await mkdir(slug,{recursive:true});await writeFile(`${slug}/index.html`,shell({title:`${title} | SpectraSec`,description,path:`${slug}/`,body}));urls.push(`${base}/${slug}/`)}
await mkdir('en',{recursive:true});await writeFile('en/index.html',shell({title:'NIS2 applicability assessment | SpectraSec',description:'English NIS2 scope, size and jurisdiction assessment.',path:'en/',body:'<h1>NIS2 applicability assessment</h1><p>Screen EU baseline scope, entity type, size, special routes and jurisdiction, then export a decision record.</p>'}));
await mkdir('es',{recursive:true});await writeFile('es/index.html',shell({title:'Evaluación de aplicabilidad NIS2 | SpectraSec',description:'Evaluación en español del alcance, tamaño y jurisdicción NIS2.',path:'es/',lang:'es',body:'<h1>Evaluación de aplicabilidad NIS2</h1><p>Analiza alcance europeo, tipo de entidad, tamaño, vías especiales y jurisdicción, y exporta un registro de decisión.</p>'}));
for(const[code,[name,authority,url]]of Object.entries(COUNTRIES)){const slug=name.toLowerCase().replaceAll(' ','-');const verified=code==='ES';await mkdir(slug,{recursive:true});const canonical=`${base}/${slug}/`;const robots=verified?'index,follow':'noindex,follow';const status=verified?'Spain module includes differentiated national references; verify every source before reliance.':'National module pending. The tool currently provides the EU baseline and does not claim complete national intelligence.';await writeFile(`${slug}/index.html`,shell({title:`NIS2 applicability in ${name} | SpectraSec`,description:`NIS2 EU-baseline scope assessment and national-module status for ${name}.`,path:`${slug}/`,robots,body:`<p>NIS2 · COUNTRY INTELLIGENCE</p><h1>NIS2 applicability in ${name}</h1><p>Assess activity, entity type, size, special routes and cross-border establishment.</p><p class="note"><strong>${status}</strong> Directory reviewed ${REVIEWED}.</p><h2>Official verification</h2><p><a href="${url}">${authority}</a></p><p><a href="${base}/?lang=en&country=${code}">Open ${name} scope screen</a> · <a href="${base}/?lang=es&country=${code}">Abrir en español</a></p>`}));if(verified)urls.push(canonical)}
await writeFile('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${x}</loc></url>`).join('')}</urlset>`);
